version: "3"
services:
  navidrome:
    image: navidrome/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options inside the environment. See config sheet for more options:
      # https://www.navidrome.org/docs/usage/configuration-options/
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "./music:/music:ro" # Navidrome mounts music as read-only by default, but you may need it rw if you want to use the sidecar

  sidecar-api:
    image: ghcr.io/Henry-Turtle/glyph-api:main
    container_name: glyph-api
    # Default to 3 workers if the user doesn't specify

    ports:
      - "4534:8080"
    restart: unless-stopped
    environment:
      # Set your custom API key
      - API_KEY=my-super-secret-api-key
      # Maximum concurrent yt-dlp downloads (defaults to 3, max limit 10)
      - MAX_DOWNLOAD_WORKERS=3
    volumes:
      # Navidrome's database must be strictly mounted as Read-Only to securely resolve Subsonic IDs
      - "./data:/data:ro"
      # The sidecar explicitly mounts music as Read-Write to physically alter ID3 tags and save downloads
      - "./music:/music:rw"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Use cron syntax: Seconds Minutes Hours DayOfMonth Month DayOfWeek
      # This schedules checks for 4:00 AM every single day to prevent disruptions
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
    restart: unless-stopped
